### ISSUE TITLE
Which PsyNeuLink branch/release to use?

### ISSUE THREAD

**Issue by pgleeson** [ModECI/MDFTests#7]
@kmantel It would be great to know which PNL branch has the latest version of the JSON MDF export. Testing install/compatibility between the various backends here: https://travis-ci.com/github/ModECI/MDFTests/jobs/486591423

**Comment by pgleeson** [comment]
Also, getting errors with `pip install psyneulink` on python 3.9. Is that supported?

**Comment by kmantel** [comment]
> Also, getting errors with `pip install psyneulink` on python 3.9. Is that supported?

I think this is likely related to psyneulink depending on Gpy down the line, which hasn't made a pip release for 3.9 compatibility yet. Using an updated but unreleased branch should work until then, see https://github.com/SheffieldML/GPy/issues/881#issuecomment-775201664

**Comment by kmantel** [comment]
> @kmantel It would be great to know which PNL branch has the latest version of the JSON MDF export. Testing install/compatibility between the various backends here: https://travis-ci.com/github/ModECI/MDFTests/jobs/486591423

The format was updated by https://github.com/PrincetonUniversity/PsyNeuLink/pull/1851, so the last commit supporting the original format is https://github.com/PrincetonUniversity/PsyNeuLink/commit/d2bab6e95ea4610625cc7e42c7babec4af86e93a. 

Any further changes should be considered latest when they reach the 'master' branch, and in the future I'll make a point of remembering to reference the breaking change in any updates to this repo.

**Comment by pgleeson** [comment]
Tests running fine now and tested on PsyNeuLink branch mdf
